# -*- coding: utf-8 -*-
"""LIONESS (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-KAFsIo5iLcHRXzvzCQml1V5ck6ZxKnD
"""

import argparse
import os
import subprocess
import sys

def install_if_missing(package_name):
    try:
        __import__(package_name)
        print(f" '{package_name}' is already installed.")
    except ImportError:
        print(f" Installing '{package_name}'...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", package_name])

# Mapping between PyPI package names and import names
packages = {
    "netZooPy": "netZooPy",
    "matplotlib": "matplotlib",
    "pandas": "pandas",
    "numpy": "numpy"
}

for pip_name, import_name in packages.items():
    install_if_missing(import_name)
from netZooPy.lioness import Lioness
from netZooPy.lioness.analyze_lioness import AnalyzeLioness
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from netZooPy.panda import Panda

# Argomenti da riga di comando
# GenNet ISN input: matrice pazienti x geni da make_isn_input.py.
# Orientation samples_x_genes (righe = patient_id, colonne = gene), che e' cio' che
# exp_data.corr() qui sotto si aspetta. I geni (colonne) sono il set consenso multi-seed.
#   python lioness.py --input <csv> --outdir <cartella>
parser = argparse.ArgumentParser(
    description="LIONESS ISN da matrice GenNet (pazienti x geni).")
parser.add_argument("--input", default="results/isn_input/isn_input_top50_seed42.csv",
                    help="CSV pazienti x geni (default: top50 seed42).")
parser.add_argument("--outdir", default=".",
                    help="Cartella di output (default: cartella corrente). "
                         "Isola i file a nome fisso prodotti da run diversi.")
cli_args = parser.parse_args()

file_path = os.path.abspath(cli_args.input)   # assoluto prima del chdir
os.makedirs(cli_args.outdir, exist_ok=True)
os.chdir(cli_args.outdir)                      # gli output (nomi fissi) finiscono qui
print(f"LIONESS input : {file_path}")
print(f"LIONESS outdir: {os.getcwd()}")

# Read the CSV file (assuming first column is gene/sample names)
expression_data = pd.read_csv(file_path, index_col=0)

# Display the first few rows to verify data loading
print(expression_data.head())

# Load the expression data (genes as rows, samples as columns)
exp_data = pd.read_csv(file_path, index_col=0) 

# Create a prior network from the expression data (gene-gene correlations)
prior_network = exp_data.T  # Transpose: genes as columns, samples as rows

# Compute the gene-gene correlation matrix
corr_matrix = exp_data.corr()

# Generate all possible gene pairs
gene_names = corr_matrix.columns
pairs = pd.MultiIndex.from_product([gene_names, gene_names], names=['source', 'target'])

# Create a DataFrame for motif data
motif_data = pd.DataFrame(index=pairs)
motif_data['weight'] = (corr_matrix.values.flatten() > 0).astype(int)  # Assign 1 if positive correlation

# Reset the index to get 'source' and 'target' columns
motif_data.reset_index(inplace=True)

# Display the first few rows of the motif data
print("Motif Data Preview:")
print(motif_data.head())

# Run PANDA to infer networks
panda_obj = Panda(
    prior_network,
    motif_data,
    None,
    computing='cpu',
    remove_missing=False,
    keep_expression_matrix=True,
    save_memory=False,
    modeProcess='legacy'
)

# Run LIONESS to estimate sample-specific networks
lioness_obj = Lioness(panda_obj)  # Uses PANDA output

# Optional: Analyze and visualize top network interactions
# analyze_lioness_obj = AnalyzeLioness(lioness_obj)
# analyze_lioness_obj.top_network_plot(top=10, file="lioness_top_10.png")

panda_obj.export_panda_results

class CustomAnalyzePanda:
    """
    Custom class to analyze and plot PANDA networks.

    Parameters
    -----------
    panda_data : object
        PANDA object containing gene interaction results.
    """
    def __init__(self, panda_data):
        """
        Initializes an instance of CustomAnalyzePanda.
        """
        if not hasattr(panda_data, 'export_panda_results'):
            raise AttributeError("Panda object does not contain the export_panda_results attribute.\n"
                                 "Run PANDA with the flag release_memory=False")

        # Load PANDA results into a DataFrame
        self.panda_results = pd.DataFrame(panda_data.export_panda_results,
                                          columns=['tf', 'gene', 'motif', 'force'])

    def top_network_plot(self, top=100, file='panda_top_100.png'):
        """
        Plots the top gene-gene interactions.

        Parameters
        -----------
        top : int (default=100)
            Number of top interactions to visualize.
        file : str (default='panda_top_100.png')
            File name to save the network plot.
        """
        # Sort by 'force' and remove self-interactions
        subset_panda_results = self.panda_results.sort_values(by=['force'], ascending=False)
        subset_panda_results = subset_panda_results[subset_panda_results['tf'] != subset_panda_results['gene']]
        subset_panda_results = subset_panda_results[:top]  # Select top interactions

        # Shape data for visualization
        self.__shape_plot_network(subset_panda_results, file)

    def __shape_plot_network(self, subset_panda_results, file='panda.png'):
        """
        Prepares data for network visualization.

        Parameters
        ___________
        subset_panda_results : DataFrame
            Filtered PANDA network data.
        file : str (default='panda.png')
            File name to save the network plot.
        """
        # Get unique gene names
        unique_genes = list(set(subset_panda_results['tf']) | set(subset_panda_results['gene']))
        unique_genes_df = pd.DataFrame({'name': unique_genes})
        unique_genes_df['index'] = unique_genes_df.index

        # Merge indices with the main dataframe
        subset_panda_results = subset_panda_results.merge(unique_genes_df,
                                                          left_on='tf', right_on='name')
        subset_panda_results.rename(columns={'index': 'tf_index'}, inplace=True)
        subset_panda_results.drop(columns=['name'], inplace=True)

        subset_panda_results = subset_panda_results.merge(unique_genes_df,
                                                          left_on='gene', right_on='name')
        subset_panda_results.rename(columns={'index': 'gene_index'}, inplace=True)
        subset_panda_results.drop(columns=['name'], inplace=True)

        # Prepare edges for visualization
        links = subset_panda_results[['tf_index', 'gene_index', 'force']]

        # Create and save the network plot
        self.__create_plot(unique_genes_df, links, file)

    def __create_plot(self, unique_genes, links, file='panda.png'):
        """
        Creates and saves a network plot using NetworkX.

        Parameters
        ___________
        unique_genes : DataFrame
            Unique gene list.
        links : DataFrame
            Filtered edges with weights.
        file : str (default='panda.png')
            File name to save the network plot.
        """
        # Create a NetworkX graph
        g = nx.Graph()
        g.add_nodes_from(unique_genes['index'])

        # Add weighted edges
        edges = [(row['tf_index'], row['gene_index'], row['force'] / 200)
                 for _, row in links.iterrows()]
        g.add_weighted_edges_from(edges)

        # Create labels
        labels = {row['index']: row['name'] for _, row in unique_genes.iterrows()}

        # Generate network layout
        pos = nx.spring_layout(g, seed=42)

        # Draw the network
        plt.figure(figsize=(10, 10))
        nx.draw_networkx(g, pos, labels=labels,
                         node_size=20, font_size=6,
                         alpha=0.3, width=0.5, linewidths=0.5)

        # Remove axes and save the figure
        plt.axis('off')
        plt.savefig(file, dpi=300)
        plt.close()

import networkx as nx
from netZooPy.panda.analyze_panda import AnalyzePanda
import matplotlib.pyplot as plt

analyze_lioness_obj = AnalyzeLioness(lioness_obj)
analyze_lioness_obj.export_panda_results['force'] = analyze_lioness_obj.lioness_results.iloc[:,2]

plot = CustomAnalyzePanda(analyze_lioness_obj)
plot.top_network_plot(10, "lioness_top_10.png")

plot.top_network_plot(100, "lioness_top_100.png")

import pandas as pd

# 1. Extract the labeled data (TF, gene, and all samples)
labeled_data = analyze_lioness_obj.lioness_results.copy()

# 2. Rename sample columns for clarity (optional)
sample_columns = labeled_data.columns[2:]  # Columns '1' to '50'
labeled_data.columns = ['tf', 'gene'] + [f'Sample_{i}' for i in range(1, len(sample_columns)+1)]

# 3. Save to CSV (with headers)
output_path = "labeled_lioness_data.csv"
labeled_data.to_csv(output_path, index=False)

print(f"Labeled data saved to: {output_path}")

